apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: believe
spec:
  containers:
  - name: busybox
    image: radial/busyboxplus:curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
